export { default as Landing } from './Landing';
export { default as NoPage } from './NoPage';
export { default as Layout } from './NoPage';
export { default as Blog} from './Blog/Blog';
export { default as Products} from './Products/Products';
export { default as Preorder} from './Preorder/Preorder';
export { default as Login} from './Auth/Login';
export { default as Register} from './Auth/Register';
export { default as Reset} from './Auth/Reset';
export { default as Admin} from './Admin/Admin';